"""Provision Arga digital twins and emit Fixpoint environment variables.

Arga twins are stateful, API-compatible replicas of Stripe, Gmail, Slack,
HubSpot and Google Drive. This script is a thin wrapper around the Arga CLI:

    1. `arga previews twins provision --twins stripe,gmail,slack,hubspot,google_drive --wait`
    2. point Fixpoint at the returned URLs.

Because the exact CLI output shape can change, this script accepts the twin
endpoints either as flags or from a JSON file, and writes a `.env.arga` snippet.
It never fails the demo: if the Arga CLI is unavailable it prints the manual
steps instead.

Usage:
    python -m scripts.arga_provision --from-json twins.json
    python -m scripts.arga_provision \
        --stripe-url https://... --stripe-token sk_test_... \
        --gmail-url https://...  --gmail-token ya29... \
        --slack-url https://...  --slack-token xoxb-... \
        --hubspot-url https://... --hubspot-token pat-... \
        --drive-url https://...  --drive-token ya29...

Then:  FIXPOINT_PROVIDER_BACKEND=arga  and source .env.arga
"""

from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
from pathlib import Path

SERVICES = {
    "stripe": "stripe",
    "gmail": "gmail",
    "slack": "slack",
    "hubspot": "hubspot",
    "drive": "drive",
}
TWIN_NAMES = "stripe,gmail,slack,hubspot,google_drive"


def _try_cli_provision() -> dict[str, str] | None:
    """Best-effort CLI provisioning. Returns a mapping if Arga is installed."""
    if shutil.which("arga") is None:
        return None
    print(f"$ arga previews twins provision --twins {TWIN_NAMES} --wait")
    try:
        result = subprocess.run(  # noqa: S603 - fixed argv, no shell
            ["arga", "previews", "twins", "provision", "--twins", TWIN_NAMES, "--wait"],
            capture_output=True,
            text=True,
            timeout=300,
            check=False,
        )
    except (OSError, subprocess.SubprocessError) as error:
        print(f"arga CLI could not be run: {error}")
        return None
    print(result.stdout or result.stderr)
    return None  # output parsing is deliberately left to --from-json / flags


def _env_lines(values: dict[str, str]) -> str:
    lines = [
        "# Arga digital twins (generated by scripts/arga_provision.py)",
        "FIXPOINT_PROVIDER_BACKEND=arga",
    ]
    for service in SERVICES:
        url = values.get(f"{service}_url", "")
        token = values.get(f"{service}_token", "")
        if url:
            lines.append(f"FIXPOINT_ARGA_{service.upper()}_URL={url}")
        if token:
            lines.append(f"FIXPOINT_ARGA_{service.upper()}_TOKEN={token}")
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Provision Arga twins for Fixpoint")
    parser.add_argument("--from-json", type=Path, help="JSON file with service url/token values")
    for service in SERVICES:
        parser.add_argument(f"--{service}-url", default="")
        parser.add_argument(f"--{service}-token", default="")
    parser.add_argument("--out", type=Path, default=Path(".env.arga"))
    args = parser.parse_args(argv)

    values: dict[str, str] = {}
    if args.from_json and args.from_json.is_file():
        values.update(json.loads(args.from_json.read_text(encoding="utf-8")))
    for service in SERVICES:
        url = getattr(args, f"{service}_url")
        token = getattr(args, f"{service}_token")
        if url:
            values[f"{service}_url"] = url
        if token:
            values[f"{service}_token"] = token

    if not values:
        _try_cli_provision()
        print(
            "\nNo twin endpoints supplied. Provide --from-json or the per-service\n"
            "flags, or paste the URLs printed by the Arga CLI. Example JSON:\n"
            '  { "stripe_url": "https://...", "stripe_token": "sk_test_...",\n'
            '    "gmail_url": "https://...", "gmail_token": "ya29...",\n'
            '    "slack_url": "https://...", "slack_token": "xoxb-...",\n'
            '    "hubspot_url": "https://...", "hubspot_token": "pat-...",\n'
            '    "drive_url": "https://...", "drive_token": "ya29..." }'
        )
        return 1

    args.out.write_text(_env_lines(values), encoding="utf-8")
    print(f"\nWrote {args.out}. Set FIXPOINT_PROVIDER_BACKEND=arga and start the app.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
